### ISSUE TITLE
Add ability to attach to multiple RLB containers

### ISSUE THREAD

**Issue by umputun** [umputun/rlb-stats#3]
In some practical cases running multiple RLBs is a thing. For instance, radio-t.com does it for http and https. In such cases, the list of destinations (redirects target) may match by (some) hostnames but be different from the protocol point of view, i.e. http vs https.

Stats should allow repeated `container_name` param as well as ENV with a separator. Aggregated stats should combine from all containers and match by server ignoring the protocol part.

**Comment by paskal** [comment]
Resolving as addressed in #6 via switching to HTTP insert instead of reading logs from container(s).
