### ISSUE TITLE
Failed attempt to integrate

### ISSUE THREAD

**Issue by umputun** [umputun/rlb-stats#4]
I have tried (and failed) to add stats into existing compose serving rlb(s) as well as some other things

This is the section:

```
  rlb-stats:
    image: umputun/rlb-stats:master
    hostname: rlb-stats
    restart: always
    container_name: rlb-stats
    logging: *default_logging

    volumes:
      - ./var/rlb-stats:/srv/var
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINER_NAME=rlb-https
      - BOLT_FILE=/srv/var/stats.db
      - DEBUG=true
```

And this is nginx part:

```
  location /rlb/ {
      proxy_set_header    X-Real-IP $remote_addr;
      proxy_set_header    Host $host;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass          http://rlb-stats:8000/;
      proxy_redirect      off;
  }
```

In a result I got container up and running, however, UI is ... strange.

<img width="1228" alt="w36lg5r7v9-20191101-213949" src="https://user-images.githubusercontent.com/535880/68064926-2be09580-fcf0-11e9-91de-3c4d4410eff5.png">

_I guess the images are missing because the path is not expcting to run behind a proxy with URL rewrite (absolute?), or maybe some issue with my nginx part_

Logs are strange-looking (two different formats?), seems to ignore DEBUG flag, and don't help at all as I see are those misleading records:

```
2019/11/01 21:34:35 "GET http://stats.radio-t.com/ HTTP/1.0" from 172.18.0.16:49190 - 200 1565B in 1.962575ms
2019/11/01 21:36:16 "GET http://localhost:8080/api/candle?from=2019-10-25T21%3A36%3A16-05%3A00&to=2019-11-01T21%3A36%3A16-05%3A00&aggregate=16h48m0s HTTP/1.1" from 127.0.0.1:50232 - 200 5B in 101.255µs
2019/11/01 21:36:16 "GET http://stats.radio-t.com/ HTTP/1.0" from 172.18.0.16:49568 - 200 1565B in 3.330988ms
2019/11/01 21:39:41 "GET http://localhost:8080/api/candle?from=2019-10-25T21%3A39%3A41-05%3A00&to=2019-11-01T21%3A39%3A41-05%3A00&aggregate=16h48m0s HTTP/1.1" from 127.0.0.1:50990 - 200 5B in 112.017µs
2019/11/01 21:39:41 "GET http://stats.radio-t.com/ HTTP/1.0" from 172.18.0.16:50326 - 200 1565B in 4.439097ms
```

Full url behind the proxy is just wrong, this is not `http://stats.radio-t.com/ ` but `http://stats.radio-t.com/rlb` but in any case there is no point of showing it istead of the one hits the service, i.e. `GET /`. Format of internal calls is not URL friendy and not human friendly. The date fromat can be made much more redable.

In addition I see no good reason for non-standard default web port 8000. Good-old 80 inside of container will be more expected

**Comment by paskal** [comment]
API left on port 8080, UI moved from 8000 to 80.

**Comment by umputun** [comment]
I'd suggest more radical change - combine both servers and separate them on routes level. I.e. everything for API will be detected by "/api" prefix and the web will be everything else
