### ISSUE TITLE
Simplify log injection

### ISSUE THREAD

**Issue by umputun** [umputun/rlb-stats#6]
The current way to listen for containers is cool and generic. However, it looks too generic to me, hard to set up right (with proper regexp), and it is also coupling stats to logs formats from RLB, which is also not a good thing (too fragile).

There is a security concern as well - mapping `docker.sock` is not something we want to do if there is any safer way. 

Proposed solution:

1. Get rid of all docker-level log reading
1. Switch to direct injection from RLB and accept [LogRecord](https://github.com/umputun/rlb/blob/master/app/server/rlb_server.go#L40)
1. To make it possible add REST endpoint on stats side

see [submitStats](https://github.com/umputun/rlb/blob/master/app/server/rlb_server.go#L140) fro more details

_btw, this will also adress #3 automatically_

**Comment by paskal** [comment]
https://github.com/umputun/rlb-stats/commit/1d236113b2a54c1abae3697f123188f526ff8d94 is first attempt to make this change. It introduces `/api/insert` POST endpoint.

**Comment by paskal** [comment]
Tests are written, also I've tested everything locally with `rlb` and it works. After I'll have confirmation of things working in production as expected, I'll clean up Docker reading code.

**Comment by umputun** [comment]
Cool. However, I'd suggest removing unused code before the deployment. This version hopefully will work and we don't want to redeploy for cleanups.

**Comment by paskal** [comment]
Cleanup is done, please review https://github.com/umputun/rlb-stats/blob/master/app/web/server.go#L47-L57: which limit should we have on `/api/insert` endpoint?

**Comment by umputun** [comment]
10/s won't be enough for the insert endpoint. You better make it more relaxed for this one, 100 should do.
